fordFulkerson: fordFulkerson.cpp
	g++ fordFulkerson.cpp -o fordFulkerson

capacityScaling: capacityScaling.cpp
	g++ capacityScaling.cpp -o capacityScaling

dinics: dinics.cpp
	g++ dinics.cpp -o dinics

edmondsKarp: edmondsKarp.cpp
	g++ edmondsKarp.cpp -o edmondsKarp

clean:
	rm fordFulkerson dinics edmondsKarp capacityScaling